name: myvault
description: A simple Flutter password manager
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6  
  encrypt: ^5.0.1  
  flutter_secure_storage: ^9.0.0
  uuid: ^4.0.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true